
version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    command: flask run --host=0.0.0.0 --port=4000
    depends_on:
      - mongo
    restart: always  # Ensure the app restarts on failure

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: kjxsofttechreport
      MONGO_INITDB_ROOT_PASSWORD: mU7IoCqlbWJQU2iT
